apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisMaster.service.name }}
  labels:
    app: {{ .Values.redisMaster.service.labels.app }}
    tier: {{ .Values.redisMaster.service.labels.tier }}
    role: {{ .Values.redisMaster.service.lables.role }}
spec:
  ports:
  - port: {{ .Values.redisMaster.service.port }}
    targetPort: {{ .Values.redisMaster.service.targetPort }}
  selector:
    app: {{ .Values.redisMaster.service.selector.app }}
    tier: {{ .Values.redisMaster.service.selector.tier }}
    role: {{ .Values.redisMaster.service.selector.role }}