apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.redisMaster.deploiement.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.redisMaster.deploiement.selector.matchLabels.app }}
      role: {{ .Values.redisMaster.deploiement.selector.matchLabels.role }}
      tier: {{ .Values.redisMaster.deploiement.selector.matchLabels.tier }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.redisMaster.deploiement.template.labels.app }}
        role: {{ .Values.redisMaster.deploiement.template.labels.role }}
        tier: {{ .Values.redisMaster.deploiement.template.labels.tier }}
    spec:
      containers:
      - name: {{ .Values.redisMaster.deploiement.template.containers.name }}
        image: {{ .Values.redisMaster.deploiement.template.containers.image }}  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.redisMaster.deploiement.template.containers.ports.containerPort }}
---
